apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: k8s-deletion-inspector
    release: "{{ .Release.Name }}"
  name: "{{ .Release.Name }}"
spec:
  endpoints:
    - interval: 15s
      port: metrics
  selector:
    matchLabels:
      app: k8s-deletion-inspector
      release: "{{ .Release.Name }}"
